server:
  port: 8081

recipe-search:
  candidate-limit: 100
  top-k: 10
  qdrant:
    host: ${QDRANT_HOST:cf19a9b2-fef9-49a9-96b2-003c18348045.eu-central-1-0.aws.cloud.qdrant.io}
    port: ${QDRANT_GRPC_PORT:6334}
    tls: ${QDRANT_TLS:true}
    api-key: ${QDRANT_API_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6ZWVlODRkZTMtYWY1MS00YTI2LWE1YmItY2FmYjgzZGYwNTczIn0.guJ_qc5Z8SMdJUOyaZkKJRDFAu-re_0gr_1tXVA2Tqo}
    collection: recipes
    vector-name: ${QDRANT_RECIPE_VECTOR_NAME:}
    inference-model: ${QDRANT_INFERENCE_MODEL:sentence-transformers/all-minilm-l6-v2}
